### ISSUE TITLE
Provide "merge when green and approved" functionality.

### ISSUE THREAD

**Issue by rwjblue** [malleatus/nyx#3]
- [ ] poll on approval (ie don't depend on `check_x` events)
- [ ] do not merge if any review is pending

---

- [ ] test in `nyx-example` using a workflow like `merge-when-green.yml`
- [x] merge: check checks as well as statuses
- [ ] report failure by context
- [ ] finish todo tests
  - commit in multiple branches
  - commit from fork (need to get owner from status.branches; maybe parsing the URL)
  - commit in multiple prs (probably just try to merge both; it might actually work since one might be downstream of the other)
- [ ] cleanup

**Comment by rwjblue** [comment]
I think there are probably some details to work out here, but I've generally wanted this functionality a bunch of times...

**Comment by hjdivad** [comment]
@rwjblue this definitely sounds good

what's the use case where the last approver doesn't just merge themselves?  is it primarily to lower the friction for them?

or is it that they approve but tests are still running so you want to "merge if tests pass" but not wait around for them?

**Comment by rwjblue** [comment]
> what's the use case where the last approver doesn't just merge themselves? is it primarily to lower the friction for them?

Ya, it is basically a proxy for "I have reviewed this, CI is still running, but I don't want to have to sit around and wait or remember to touch it again".

**Comment by hjdivad** [comment]
yeah that sounds super nice: and have it ping the reviewer if the tests fail

**Comment by hjdivad** [comment]
https://help.github.com/en/actions/reference/events-that-trigger-workflows#webhook-events

**Comment by hjdivad** [comment]
@rwjblue you'll have to remind me where we ended up; i.e. how close is this to being something we'd want to use

**Comment by hjdivad** [comment]
use github's built in thing
